[package]
name = "pdfrip"
version = "2.0.1"
edition = "2021"
authors = ["Mufeed VH <mufeed@lyminal.space>", "Pommaq"]

[dependencies]
indicatif = "0.16.2"
log = "0.4.19"
anyhow = "1.0.72"
crossbeam = "0.8.2"
pretty_env_logger = "0.5.0"
colored = "2.0.4"
pdf = "0.8.1"
bytecount = "0.6.7"
clap = { version = "4.4.13", features = ["derive"] }

[profile.release]
lto = 'thin'
panic = 'abort'
codegen-units = 1
